version: "3"
services:
  naming-server:
    image: bproenca/netflix-eureka-naming-server:1.0
    ports:
      - "8761:8761"
    restart: always
    networks:
      - currency-compose-network

  currency-exchange-service:
    image: bproenca/currency-exchange-service:1.0
    ports:
      - "8000:8000"
    depends_on:
      - naming-server  
    networks:
      - currency-compose-network

  currency-conversion-service:
    image: bproenca/currency-conversion-service:1.0
    ports:
      - "8100:8100"
    depends_on:
      - naming-server
      - currency-exchange-service
    networks:
      - currency-compose-network

# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network:
