version: "3"
services:
  currency-exchange-service:
    image: bproenca/currency-exchange-service:1.0
    ports:
      - "8000:8000"
    deploy:
      replicas: 2
    networks:
      - currency-compose-network

  currency-conversion-service:
    image: bproenca/currency-conversion-service:1.0
    ports:
      - "8100:8100"
    environment:
      CURRENCY_EXCHANGE_URI: http://currency-exchange-service:8000
    depends_on:
      - currency-exchange-service
    networks:
      - currency-compose-network

# Networks to be created to facilitate communication between containers
networks:
  currency-compose-network:
