spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bproenca/spring-cloud-bcp-config-repo.git
server:
  port: 8888


# Para acessar as propriedades: http://localhost:8888/limits-service/default
# [branch master] --> http://localhost:8888/limits-service/qa/master (or without last word)
# [branch br1]    --> http://localhost:8888/limits-service/qa/br1
